version: 0.2

phases:
  build:
    commands:
      - Entered the build phase...
      - mvn clean package
    
  post_build:
    commands:
      - echo Build completed  successfully on `date`
      
artifacts:
  files:
   - target/order-service.jar
  discard-paths: yes 

